### ISSUE TITLE
reduce 20160304 data bug

### ISSUE THREAD

**Issue by crawfordsm** [saltastro/polsalt#24]
Steve-

So I removed debug temporarily from my reducepoldata, and ran wavmap on the 0304 data (newly run through imred), with my previous dbfiles in the sci directory so I wouldn’t have to run specidentify again.  The first observation goes through fine, but the second (the 300-line) crashes out.

Output below, and dbfiles enclosed, in case you need them.

@knordsieck 
…

-khn-oderbolz-55-> python reducepoldata.py 20160304
host: Undefined variable.
host: Undefined variable.
SPECPOLWAVMAP
infilelist=['mxgbpP201603040043.fits', 'mxgbpP201603040044.fits', 'mxgbpP201603040045.fits', 'mxgbpP201603040046.fits', 'mxgbpP201603040047.fits', 'mxgbpP201603040048.fits', 'mxgbpP201603040049.fits', 'mxgbpP201603040050.fits', 'mxgbpP201603040051.fits', 'mxgbpP201603040052.fits', 'mxgbpP201603040053.fits', 'mxgbpP201603040054.fits', 'mxgbpP201603040055.fits', 'mxgbpP201603040056.fits', 'mxgbpP201603040057.fits', 'mxgbpP201603040058.fits', 'mxgbpP201603040059.fits', 'mxgbpP201603040060.fits', 'mxgbpP201603040061.fits', 'mxgbpP201603040062.fits']
linelistlib= automethod=Matchlines function=legendre order=3
logfile=specpol20160304.log

2016-03-08 13:47:12 MESSAGE ------------------------------------------
Starting specpolwavmap

Pysalt Version: v0.5dev

For images: 43 44 45 46 47 48 49 50 51 52 53
  Use Arc    53

For images: 54 55 56 57 58 59 60 61 62
  Use Arc    62
[-989.59216796  996.74579026]

ARC: image 53 GRATING PG0900 GRANG   12.500 ARTIC   25.000 LAMP ThAr
  Split Row:  518

  Wavl coeff rows:  O      13     E       5
  Bottom, top row:  O   62  482   E   47  447

  Slit axis row:    O     262     E     247
  Bottom, top row:  O   28  497   E   11  484

Output file wmxgbpP201603040043.fits
Output file wmxgbpP201603040044.fits
Output file wmxgbpP201603040045.fits
Output file wmxgbpP201603040046.fits
Output file wmxgbpP201603040047.fits
Output file wmxgbpP201603040048.fits
Output file wmxgbpP201603040049.fits
Output file wmxgbpP201603040050.fits
Output file wmxgbpP201603040051.fits
Output file wmxgbpP201603040052.fits
Output file wmxgbpP201603040053.fits
[-953.08293255  959.97518951]

ARC: image 62 GRATING PG0300 GRANG    5.375 ARTIC   10.750 LAMP Ar
  Split Row:  515
2016-03-08 13:47:27 ERROR --------------------------------------------

invalid value encountered in less

2016-03-08 13:47:27 MESSAGE ------------------------------------------
specpolwavmap aborted

Traceback (most recent call last):
  File "reducepoldata.py", line 41, in <module>
    specpolwavmap(infile_list, linelistlib=linelistlib, logfile=logfile)
  File "/d/carol/Synched/software/SALT/polsaltcopy/polsalt/specpolwavmap.py", line 95, in specpolwavmap
    log=log)
  File "/d/carol/Synched/software/SALT/polsaltcopy/polsalt/specpolwavmap.py", line 209, in pol_wave_map
    mask = (y < edgerow_od[o,0] + drow_oc[o]) | (y > edgerow_od[o,1] + drow_oc[o])
FloatingPointError: invalid value encountered in less
-khn-oderbolz-55->

From: Steve Crawford [mailto:notifications@github.com]
Sent: Sunday, March 06, 2016 7:19 PM
To: saltastro/polsalt
Subject: [polsalt] Wavmap rewrite (#17)

Re-writes specpolwavmap and splits out a number of functions include one for splitting the images and correcting the distortion.

---

You can view, comment on, or merge this pull request online at:

  #17

Commit Summary
-   function to split into two beams
-   general functions for specpol
-   re-organization of specpolwavmap
-   changed import for configmap
-   adding specpolwollaston
-   updates for correct_wollaston

File Changes
-   M polsalt/specpolextract.pyhttps://github.com/saltastro/polsalt/pull/17/files#diff-0 (2)
-   A polsalt/specpolsplit.pyhttps://github.com/saltastro/polsalt/pull/17/files#diff-1 (68)
-   A polsalt/specpolutils.pyhttps://github.com/saltastro/polsalt/pull/17/files#diff-2 (139)
-   M polsalt/specpolwavmap.pyhttps://github.com/saltastro/polsalt/pull/17/files#diff-3 (354)
-   A polsalt/specpolwollaston.pyhttps://github.com/saltastro/polsalt/pull/17/files#diff-4 (108)

Patch Links:
-   https://github.com/saltastro/polsalt/pull/17.patch
-   https://github.com/saltastro/polsalt/pull/17.diff

—
Reply to this email directly or view it on GitHub<#17>.
# WS: Wavelength solution for image arc_53_0.fits
# The following parameters were used in determining the solution:
# name=arc_53_0.fits
# time-obs=2016-03-05 00:17:17.458
# instrument=RSS
# grating=PG0900
# graang=12.5
# gratilt=12.5
# arang=24.900345
# artilt=25.0
# filter=PC03200
# Function=legendre
# Order=3
# Starting Data

62.00 3.198443e+03 1.011374e+00 -2.340793e-06 -9.308172e-10
62.50 3.219404e+03 9.655592e-01 1.786167e-05 -3.360098e-09
162.50 3.085097e+03 1.171630e+00 -4.933598e-05 2.996534e-09
182.00 3.234103e+03 9.510541e-01 1.970158e-05 -3.166107e-09
222.00 3.193345e+03 1.030133e+00 -1.064332e-05 3.977321e-11
242.00 3.211082e+03 9.990717e-01 4.874825e-07 -1.045125e-09
282.00 3.218250e+03 9.773492e-01 1.193266e-05 -2.480664e-09
302.00 3.192422e+03 1.030158e+00 -9.000673e-06 -2.652197e-10
322.00 3.226519e+03 9.637017e-01 1.636518e-05 -2.887277e-09
342.00 3.184080e+03 1.044910e+00 -1.462223e-05 3.523073e-10
362.50 3.215919e+03 9.667319e-01 2.053159e-05 -3.809734e-09
382.00 3.164693e+03 1.078621e+00 -2.666523e-05 1.530341e-09
442.00 3.160444e+03 1.094487e+00 -3.680000e-05 2.917248e-09
462.50 3.154972e+03 1.119438e+00 -5.042816e-05 4.731679e-09
482.00 3.135065e+03 1.117716e+00 -3.950342e-05 2.773257e-09
# WS: Wavelength solution for image arc_53_1.fits
# The following parameters were used in determining the solution:
# name=arc_53_1.fits
# time-obs=2016-03-05 00:17:17.458
# instrument=RSS
# grating=PG0900
# graang=12.5
# gratilt=12.5
# arang=24.900345
# artilt=25.0
# filter=PC03200
# Function=legendre
# Order=3
# Starting Data

47.50 3.210329e+03 9.816204e-01 1.174219e-05 -2.642391e-09
147.50 3.194477e+03 1.027361e+00 -7.986807e-06 -4.932778e-10
247.50 3.203427e+03 1.010067e+00 -2.851675e-07 -1.323270e-09
347.50 3.204952e+03 1.008647e+00 -1.111142e-07 -1.337367e-09
447.50 3.207742e+03 1.011184e+00 -4.442206e-06 -5.627353e-10
# WS: Wavelength solution for image arc_62_0.fits
# The following parameters were used in determining the solution:
# name=arc_62_0.fits
# time-obs=2016-03-05 01:04:35.879
# instrument=RSS
# grating=PG0300
# graang=5.375
# gratilt=5.375
# arang=10.63908
# artilt=10.75
# filter=PC03850
# Function=legendre
# Order=3
# Starting Data

51.00 9.520645e+02 3.823789e+00 -2.975744e-04 3.208139e-08
71.00 1.155420e+03 3.452180e+00 -1.489132e-04 1.459925e-08
91.00 1.573660e+03 2.730112e+00 1.267797e-04 -1.676602e-08
111.00 1.157895e+03 3.447827e+00 -1.460744e-04 1.416595e-08
131.00 1.383278e+03 3.071073e+00 -7.703533e-06 -8.782349e-10
171.00 1.300243e+03 3.242454e+00 -7.955664e-05 7.725639e-09
191.00 1.264261e+03 3.257915e+00 -7.109907e-05 5.465059e-09
211.00 1.567501e+03 2.781550e+00 9.344245e-05 -1.135913e-08
231.00 1.434623e+03 2.956307e+00 4.601010e-05 -7.955287e-09
251.00 1.455160e+03 2.909085e+00 6.828574e-05 -1.095359e-08
271.00 1.384662e+03 3.056581e+00 5.134708e-06 -3.225256e-09
291.00 1.409818e+03 3.013328e+00 1.767178e-05 -3.926773e-09
311.00 1.450757e+03 2.922304e+00 6.136339e-05 -9.966496e-09
331.00 1.386481e+03 3.055997e+00 1.514627e-06 -2.131149e-09
351.00 1.469784e+03 2.873482e+00 8.395383e-05 -1.281438e-08
371.00 1.357809e+03 3.116399e+00 -2.384058e-05 8.447303e-10
391.00 1.393197e+03 3.036442e+00 1.289554e-05 -3.998003e-09
411.00 1.330541e+03 3.170368e+00 -4.843421e-05 4.089949e-09
431.00 1.395470e+03 3.036625e+00 7.935993e-06 -2.662271e-09
451.00 1.685547e+03 2.533296e+00 2.021749e-04 -2.514568e-08
471.00 1.288171e+03 3.248204e+00 -7.968789e-05 7.728048e-09
491.00 1.271812e+03 3.237921e+00 -6.382524e-05 4.849522e-09
# WS: Wavelength solution for image arc_62_1.fits
# The following parameters were used in determining the solution:
# name=arc_62_1.fits
# time-obs=2016-03-05 01:04:35.879
# instrument=RSS
# grating=PG0300
# graang=5.375
# gratilt=5.375
# arang=10.63908
# artilt=10.75
# filter=PC03850
# Function=legendre
# Order=3
# Starting Data

19.00 1.426130e+03 2.973040e+00 3.943887e-05 -7.161194e-09
39.00 1.420892e+03 2.983924e+00 3.613224e-05 -6.914930e-09
59.00 1.463187e+03 2.897951e+00 7.088439e-05 -1.081088e-08
79.00 1.436203e+03 2.957181e+00 4.684500e-05 -8.151219e-09
99.00 1.403134e+03 3.024675e+00 1.876383e-05 -4.806615e-09
119.00 1.391925e+03 3.051313e+00 6.296245e-06 -3.136230e-09
139.00 1.424424e+03 2.988209e+00 3.159508e-05 -6.026940e-09
159.00 1.374832e+03 3.085340e+00 -6.874603e-06 -1.716492e-09
179.00 1.395009e+03 3.049091e+00 6.525801e-06 -3.096482e-09
199.00 1.531170e+03 2.769170e+00 1.257962e-04 -1.765131e-08
239.00 1.417379e+03 3.001219e+00 2.871368e-05 -6.042297e-09
279.00 1.448999e+03 2.935291e+00 5.694480e-05 -9.506760e-09
299.00 1.415081e+03 3.010782e+00 2.318922e-05 -5.250658e-09
319.00 1.601635e+03 2.691838e+00 1.415477e-04 -1.821934e-08
339.00 1.535204e+03 2.763156e+00 1.270879e-04 -1.765067e-08
359.00 1.431472e+03 2.974107e+00 3.904549e-05 -7.227804e-09
379.00 1.368124e+03 3.117147e+00 -2.843114e-05 1.817069e-09
399.00 1.411807e+03 3.012348e+00 2.314190e-05 -5.359838e-09
419.00 1.441411e+03 2.950911e+00 4.939769e-05 -8.612954e-09
439.00 1.427344e+03 2.983993e+00 3.350059e-05 -6.437125e-09
459.00 1.578619e+03 2.736911e+00 1.239228e-04 -1.647356e-08

**Comment by crawfordsm** [comment]
related to #17

**Comment by crawfordsm** [comment]
@knordsieck can you confirm if this happens to all P0300 grating data or just on nights when there are two different observations?

**Comment by knordsieck** [comment]
Steve-

I have it fail the same way for two different PG0300 observations (0210 and 0304), even when I separate observations, if necessary.

Ken

**Comment by crawfordsm** [comment]
@knordsieck I can't reproduce this error on either night, running it on all the data, or using your db files.   

I've just pushed a commit to fix issue #26, but please see if that may have helped this problem.
